### PR TITLE
Bump versions and update createAuthCookies interface

### PR DESCRIPTION
**Pull request by ankithkonda**
Related to - https://github.com/OctopusDeploy/Issues/issues/7306

auth providers updates -

LdapAuthenticationProvider - https://github.com/OctopusDeploy/LdapAuthenticationProvider/pull/63
DirectoryServicesAuthenticationProvider - https://github.com/OctopusDeploy/DirectoryServicesAuthenticationProvider/pull/70
OpenIDConnectAuthenticationProviders - https://github.com/OctopusDeploy/OpenIDConnectAuthenticationProviders/pull/63
UsernamePasswordAuthenticationProvider - https://github.com/OctopusDeploy/UsernamePasswordAuthenticationProvider/pull/22
GuestAuthenticationProvider - https://github.com/OctopusDeploy/GuestAuthenticationProvider/pull/26

### CODE REVIEW

**Review by zentron — APPROVED** [review]
LGTM, though I'd be keen to hear @slewis74 confirm that this will have not compatibility issues anywhere else?
Presumably any user using their own forked versions will need to update their code.

**Comment by slewis74** [comment]
Are there PRs for all of the authentication providers to go with this? Could they be linked to here?

This is a hard breaking change, if you miss any one of the auth providers it'll be a hard server failure at runtime, because the server's compile won't pick it up. Exceptions in these code paths are REALLY bad, they prevent access to your Octopus instance.

A more forgiving option would be to add a new method with the updated signature and mark the existing as deprecated. New compiles of the auth extensions will start forcing down the new path but it won't cause issues at runtime if anything gets missed. I would also recommend logging warnings in the deprecated method if it gets used, to help identify anything that's been missed.

**Comment by ankithkonda** [comment]
all the auth providers have been updated with the new method. I'll link the PRs here. we're using github actions to build and release, I assume we should have a major version bump. is it just a matter of adding a commit with `+SemVer: major` in the commit message?

**Comment by ankithkonda** [comment]
replaced by https://github.com/OctopusDeploy/AuthenticationExtensibility/pull/34

**Pull request closed without merging**
